### ISSUE TITLE
New factors not visible in Settings Setup inventory columns

### ISSUE THREAD

**Issue by bmorris53** [nbentoumi/ansibledb#3]
I've started to run into issues with new custom facters as well as previously working facters not showing up in the list of available facters to set as columns for the inventory page.  Could you point me in a way to debug/troubleshoot this?

If I go to the facters page they work there.  And I also confirm on the host pages that most hosts have a value set for the facters I am trying to set as columns

**Comment by bmorris53** [comment]
I believe I found the problem, the model manage_inventory_columns, the query_keys and subsequent cursor used is finding one of my hosts that has almost no defined facters.  I need to find a way to change this so it uses some kind of control host to get all available facters keys.

**Comment by bmorris53** [comment]
I fixed this by updating the manage_inventory_columns model to use this for the query_keys value, ensuring I don't use a host that is there for tracking only:

```
query_keys = { "ansible_facts.groups": {"$ne": 'tracking_only'}}
```

**Comment by bmorris53** [comment]
I fixed this by updating the manage_inventory_columns model to use this for the query_keys value, ensuring I don't use a host that is there for tracking only:

```
query_keys = { "ansible_facts.groups": {"$ne": 'tracking_only'}}
```

**Comment by nbentoumi** [comment]
Hi @bmorris53 ,
Thanks for the update.
