### ISSUE TITLE
Add your project to Awesome Ansible list if relevant

### ISSUE THREAD

**Issue by Andersson007** [nbentoumi/ansibledb#4]
Hello,

We are moving / removing projects from https://docs.ansible.com/ansible/devel/community/other_tools_and_programs.html to the [Awesome Ansible List](https://github.com/ansible-community/awesome-ansible).

I see the last commit here was last year. If your tool is still supported and works, please add it to the [Awesome Ansible List](https://github.com/ansible-community/awesome-ansible) by opening a PR there.

Thank you!

**Comment by nbentoumi** [comment]
Thanks @Andersson007
